name: Kernel Uptime

on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday at 00:00 UTC (Adjust as needed)
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Add upstream and fetch
      run: |
        git remote add upstream https://github.com/torvalds/linux.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git merge upstream/master || echo "No upstream changes to merge"

    - name: Push changes to fork
      run: |
        git push origin main
