name: Kernel Uptime

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout fork
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 1  

    - name: Add from mainline upstream and fetch updates
      run: |
        git remote add upstream https://github.com/torvalds/linux.git
        git fetch upstream master --depth=1

    - name: Rebase from upstream Linux dev
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git rebase upstream/master || echo "✅ Nothing to rebase."

    - name: Push changes to fork (only if updated)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch origin main
        git diff --quiet HEAD origin/main || git push origin HEAD:main
