name: Sync repository from Linux kernel source tree

on:
  schedule:
    # Runs at 02:00 on the 1st of every month
    - cron: '0 2 1 * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: get full history for repository merge

    - name: Add upstream and fetch
      run: |
        git remote add upstream https://github.com/torvalds/linux.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git merge upstream/master || echo "No upstream changes to merge"

    - name: Push changes to fork repository
      run: |
        git push origin main
